dataset_frac: 1.0
epochs: 20
huggingface_dataset:  "9wimu9/ada_derana_sinhala"
dataset_dir_name: "dataset" # Directory name to save cached and processed text files
seq_length: 200
buffer_size: 10000
seed: 42
batch_size: 512
embedding_dim: 256
rnn_units: 1024
learning_rate: 0.001
train_frac: 0.95
export_dir_name: "saved_model"
checkpoints_dir_name: "training_checkpoints"
early_stopping: {monitor: "val_loss", min_delta: 0.001, patience: 3, verbose: 1, restore_best_weights: true}
