huggingface_dataset:  "9wimu9/ada_derana_sinhala"
seq_length: 200
buffer_size: 10000
seed: 42
batch_size: 512
embedding_dim: 256
rnn_units: 1024
epochs: 20
learning_rate: 0.001
train_frac: 0.95
export_dir_name: "saved_model"
dataset_frac: 1.0
